### ISSUE TITLE
I cant do a mvn clean install

### ISSUE THREAD

**Issue by JonathanBergers** [isisaddons/isis-app-neoapp#1]
Hello!
I would love to mess around with neo4j and apache isis, but i cant get this app to work.
specs: java 1.8, linux. IDE: IntelliJ.
Tried: modifying pom, clear cache etc..
When i do a mvn clean install in the neoapp directory i get an error.
I cant run datanucleus. 

error log maven:

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.datanucleus:datanucleus-maven-plugin:4.0.0-release:enhance (default) on project neoapp-dom: Error executing DataNucleus tool org.datanucleus.enhancer.DataNucleusEnhancer
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
......

Caused by: java.lang.ClassNotFoundException: org.datanucleus.enhancer.DataNucleusEnhancer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.datanucleus.maven.AbstractDataNucleusMojo.executeInJvm(AbstractDataNucleusMojo.java:309)
	... 24 more

**Comment by danhaywood** [comment]
Hi Jonathan,
thanks for the interest... however as you've discovered this is still work-in-progress.

The initial version work on this was done by [Jeremy Branham](https://github.com/jdbranham), who then went on to do most of the work in moving from DN 3.2 to DN 4.0.  That included an initial version of this neo4j version of our simpleapp demo which, as I understand it, also embeds the Neo4J server console.  

However, as you've discovered, I haven't had the chance to get it cleaned up and working.

I don't think there's much wrong with the code, and now that I know that there's someone interested, I'll try to make the time.

Cheers
Dan

**Comment by danhaywood** [comment]
OK, this demo app now runs, and the embedded server on port 7474.
There are some issues... mostly that if I get an NPE if I try to just list an object, one needs to create an instance first.  I think that's because the initialization of DataNucleus' metamodel is done lazily, which is tripping things up.
Also, the example app is only half-finished; there's a SimpleObject (from our original simpleapp archetype), but Jeremy's also added a slightly more interesting Host and IpAddress classes, that have relationships between them.  I added a bit of code so that one can add links between Host and IpAddress; these show up nicely on 7474.
Anyway, give it a play...
Cheers
Dan

**Comment by JonathanBergers** [comment]
Thanks a lot!

**Comment by danhaywood** [comment]
Some further improvements, also updated the README.
